//
//  CintricFind.h
//  Cintric
//
//  Created by Joel Green on 10/1/14.
//  Copyright (c) 2014 Cintric. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreLocation/CoreLocation.h>
#import <MapKit/MapKit.h>

@protocol CintricFindDelegate;

/**
 CintricFind enables battery efficient location monitoring 24/7.

 @discussion It will handle permissions and will update even after the user has force quit the app.
             Our testing shows that our location updates will use 2% or less of a users battery on an average day.
             To use this SDK you must request an api key from http://cintric.com

 Make sure in your appDelegate application:didFinishLaunchingWithOptions: method you call
 
 @code
 [CintricFind initWithApiKey:@"YOUR_API_KEY_HERE" andSecret:@"YOUR_SECRET_HERE"];
 @endcode
 @see http://cintric.com/documentation
 */
@interface CintricFind : NSObject

/**
 Initalize cintric location with your api key.
 If the api key is valid location updates will start.
 @param apiKey NSString : the api key you receive when creating a Cintric developer account
 @returns CintricFind : reference to self
 */
+ (CintricFind *)initWithApiKey:(NSString *)apiKey andSecret:(NSString *)secret;

/**
 Set the delegate to be notified when the locaiton updates or permissions change
 
 @param delegateResponder an object which implements the CintricFindDelegate protocol
 */
+ (void)setDelegate:(id <CintricFindDelegate>)delegateResponder;

/**
 The current location of the device.
 @discussion This should stay accurate to within 400 feet at all times.
             Some cases such as very poor reception may reduce accuracy, however this is uncommon.
             To get the lat and lon:
 @code
 CLLocation *location = [CintricFind getCurrentLocation];
 location.coordinate.latitude //CGFloat
 location.coordinate.longitude // CGFloat
 @endcode
 */
+ (CLLocation *)getCurrentLocation;

/**
 Set this to NO to turn off NSLogging. This is enabled in debug build by default.
 In production this will automatically be set to NO.
 
 @param loggingEnabled NO disables logging
 */
+ (void)setDebug:(BOOL)loggingEnabled;

/**
 Updates the location to the best accuracy availble
 
 @discussion This will trigger the didUpdateDeviceLocation delegate method.
             Although you can expect the location to stay very accurate most of the time,
             this may be useful if you want to make sure the
             location is currently at the best accuracy possible.
             Call this when first showing the users locaiton on a map.
 */
+ (void)updateLocation;

/**
 Stops all locaiton updates

 @discussion Location updates will resume if you call updateLocation or
             initWithApiKey:andSecret: (which should always be called in application:didFinishLaunchingWithOptions:)
 */
+ (void)stopUpdatingLocation;

/**
 Set a unique ID for the current user (call this on user login or app launch)

 @discussion Calling this method will allow you to better integrate with Cloud and Metrics.
             If you are using facebook login, we suggest to use the users facebook ID here.
             Otherwise use whatever unique identifying string you have for the user.
             If you don't call this method we will use our randomly generated ID for each user.

 @param idString unique user identifying string
 */
+ (void)setUniqueIdForUser:(NSString *)idString;

/**
 Enables privacy mode - no location information is sent to our servers or shared in any way (this is disabled by default)
 
 @discussion If you want to enable privacy mode, call this method immediatly after initalizing Cintric
             Make sure this method is ALWAYS called after initWithApiKey:andSecret: if you want privacy mode to stay on
             Calling this method will disable some Cintric Learn and Act functionality.
 
 @code
 [CintricFind initWithApiKey:@"YOUR_API_KEY_HERE" andSecret:@"YOUR_SECRET_HERE"];
 [CintricFind enablePrivacyMode:YES];
 @endcode
 
 @param shouldEnablePrivacy Set this to YES to enable privacy mode
 */
+ (void)enablePrivacyMode:(BOOL)shouldEnablePrivacy;

/**
 Asynchronously request an array of UUID's of users nearest to a specified coordinate.
 
 @discussion This method will send a request to the Cintric Act API to get nearby users.
             This will trigger didReceiveUsers:nearLocation: delegate method when complete.
             The array will be of user unique identifiers, which may be set by you in setUniqueIdForUser:.
             Otherwise they will be the ID's generated by our database.
             The number of users returned be count (or fewer if you don't have that many users).
             Count can not be more than 200 (a larger number will be set to 200).
 
 @param coordinate The coordinate which you are specifying for nearby users
 @param count The total number of nearby users you want returned, this will never excee 200.
 */
+ (void)requestNearestUsersToLocation:(CLLocationCoordinate2D)coordinate count:(int)count;

@end

///------------------------------------------------
/// Delegate Protocol
///------------------------------------------------

@protocol CintricFindDelegate <NSObject>

@optional

/**
 This is called whenever the location is updated.
 
 @discussion Use this to do things like update your UI, or notify your server of the location change
 You should expect the location to be at its best accuracy when this is called
 
 @param location CLLocation : the device's current location
 */
- (void)didUpdateDeviceLocation:(CLLocation *)location;

/**
 This will be called after calling requestNearestUsersToLocation:count: on successful return.
 @param userList An array of NSString user IDs (set by you or defaulted to our generated IDs).
 @param coordinate The coordinate which you specified in the request.
 */
- (void)didReceiveUsers:(NSArray *)userList nearLocation:(CLLocationCoordinate2D)coordinate;

/** This will be called if the user allows location updates */
- (void)locationServicesAuthorized;

/** 
 This will be called if the user's device can not update location.
 Some devices may be restricted, for example, by parental controls.
 Do NOT ask your user to change their settings in this case.
 */
- (void)locationServicesRestricted;

/**
 This will be called if the user denied access location services
 We recommend you ask the user to open settings and enable their locaiton services
 */
- (void)locationServicesDenied;

@end
